state_machine:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/drive"
    banana_detection_topic: "/banana_detection"
    signal_detection_topic: "/signal_detection"
    shell_points_topic: "/shell_points"
    main_loop_rate: 60.0
    lookahead_distance: 0.5
    path_request_topic: "/path_request"
    lookahead_point_topic: "/lookahead_point"
    planned_path_topic: "/planned_path"
pure_pursuit:
  ros__parameters:
    drive_topic: "/drive"
