state_machine:
  ros__parameters:
    odom_topic: "/pf/pose/odom"
    drive_topic: "/vesc/high_level/input/nav_0"
    banana_detection_topic: "/detections/banana"
    signal_detection_topic: "/detections/traffic_light"
    shell_points_topic: "/shell_points"
    main_loop_rate: 60.0
    lookahead_distance: 1.0
    path_request_topic: "/path_request"
    lookahead_point_topic: "/lookahead_point"
    planned_path_topic: "/planned_path"
pure_pursuit:
  ros__parameters:
    drive_topic: "/vesc/high_level/input/nav_1"